# Tensors 张量

张量是一种特殊的数据结构，与数组和矩阵非常相似，在Pytorch中我么使用张量来表示模型的输入和输出数据，以及模型的参数。张量是一种多维数组，它可以在GPU上运行以加速计算。

张量与Numpy的ndarrays非常相似，但张量可以在GPU或其他专用硬件上运行以加速计算。事实上，张量和numpy的ndarrays可以共享底层内存，这样可以避免数据复制，从而加速计算。张量还针对自动微分进行了优化，这是深度学习的一种常用技术，如果熟悉Numpy，那么使用张量将非常简单。

In [1]:
import torch
import numpy as np

## 初始化张量

张量可以通过多种方式进行初始化，下面是一些常见的初始化方法。

### 直接来自数据
张量可以直接从数据创建。数据类型是自动推断的。

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


### 来自NumPy数组
张量可以从NumPy数组创建，反之亦然。

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)
x_array = x_np.numpy()
print(x_array)

tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]


### 从另一个张量
新张量保留另一个张量的属性（形状、数据类型），除非显式覆盖。

In [4]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4569, 0.4040],
        [0.8684, 0.6814]]) 


### 使用随机值或常量值
`shape`是张量维度的元组。在下面的函数中，它确定输出张量的维数。

In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7122, 0.7309, 0.1254],
        [0.3602, 0.8863, 0.1028]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 张量属性

张量属性描述了它们的形状、数据类型以及存储它们的设备。

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 张量运算

[这里](https://pytorch.org/docs/stable/torch.html)全面描述了 100 多种张量运算，包括算术、线性代数、矩阵操作（转置、索引、切片）、采样等。

这些操作中的每一个都可以在 GPU 上运行（速度通常高于 CPU）。如果您使用的是 Colab，请转至运行时 > 更改运行时类型 > GPU 来分配 GPU。

默认情况下，张量是在 CPU 上创建的。我们需要使用`.to`方法显式地将张量移动到 GPU（在检查 GPU 可用性之后）。请记住，跨设备复制大张量在时间和内存方面可能会很昂贵！

In [7]:
device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
print(f"Current device: {device}")

Current device: mps


In [8]:
tensor = tensor.to(device)

尝试列表中的一些操作。如果您熟悉 NumPy API，您会发现 Tensor API 使用起来非常简单。

标准的类似 numpy 的索引和切片：

In [9]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


连接张量您可以使用`torch.cat`沿给定维度连接一系列张量。另请参见[torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html) ，这是另一个与`torch.cat`略有不同的张量连接运算符。

In [10]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


算术运算

In [11]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
# 矩阵乘矩阵的转置 方法一
y1 = tensor @ tensor.T
print(f"tensor @ tensor.T: \n {y1} \n")
# 矩阵乘矩阵的转置 方法二
y2 = tensor.matmul(tensor.T)
print(f"tensor.matmul(tensor.T): \n {y2} \n")

y3 = torch.rand_like(y1)
print(f"y3: \n {y3} \n")
# 矩阵乘矩阵的转置 方法三 将矩阵乘法的结果直接存储到一个已经存在的张量 y3 中，而不需要重新分配内存。这种方式在处理大张量时可以节省内存开销并提高性能。
torch.matmul(tensor, tensor.T, out=y3)
print(f"torch.matmul(tensor, tensor.T, out=y3): \n {y3} \n")

# This computes the element-wise product. z1, z2, z3 will have the same value
## 两个张量中的每个位置的元素逐个相乘，要求两个张量的形状一致
z1 = tensor * tensor
print(f"tensor * tensor: \n {z1} \n")
z2 = tensor.mul(tensor)
print(f"tensor.mul(tensor): \n {z2} \n")

z3 = torch.rand_like(tensor)
print(f"z3: \n {z3} \n")
torch.mul(tensor, tensor, out=z3)
print(f"torch.mul(tensor, tensor, out=z3): \n {z3}")

tensor @ tensor.T: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor.matmul(tensor.T): 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

y3: 
 tensor([[0.9986, 0.7715, 0.4549, 0.6557],
        [0.5811, 0.1962, 0.8139, 0.0939],
        [0.0758, 0.7621, 0.2436, 0.4743],
        [0.8942, 0.0020, 0.8214, 0.9899]]) 

torch.matmul(tensor, tensor.T, out=y3): 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor * tensor: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor.mul(tensor): 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

z3: 
 tensor([[0.3032, 0.4704, 0.4271, 0.3427],
        [0.7269, 0.7937, 0.3649, 0.9858],
        [0.7570, 0.7217, 0.0050, 0.6798],
        [0.2116, 0.5671, 

单元素张量如果您有一个单元素张量，例如通过将张量的所有值聚合为一个值，您可以使用item()将其转换为 Python 数值

In [12]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


就地运算将结果存储到操作数中的操作称为就地运算。它们由`_`后缀表示。例如： `x.copy_(y)` 、 `x.t_()`会更改x 。

In [13]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


> 就地操作可以节省一些内存，但在计算导数时可能会出现问题，因为历史记录会立即丢失。因此，不鼓励使用它们。

## 桥接 NumPy 和张量(Bridge with NumPy)

CPU 和 NumPy 数组上的张量可以共享其底层内存位置，改变其中一个就会改变另一个。

### 张量到 NumPy 数组

In [14]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


张量的变化反映在 NumPy 数组中。

In [15]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### 数组到张量

In [16]:
n = np.ones(5)
t = torch.from_numpy(n)

NumPy 数组中的变化反映在张量中。

In [17]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
